version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/cloudflared"
      - "/nginx"
      - "/tsdproxy"
      - "/device-tracker"
      - "/influxdb"
      - "/pingvin"
      - "/grafana"
      - "/prometheus"
      - "/cadvisor"
    schedule:
      interval: "monthly"

