version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/cloudflared"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/tsdproxy"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/device-tracker"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/influxdb"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/beszel"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/pingvin"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/grafana"
    schedule:
      interval: "monthly"

