version: 2
updates:
  # All Docker‑Compose services
  - package-ecosystem: "docker-compose"
    directories:
      - "/cloudflared"
      - "/nginx"
      - "/tsdproxy"
      - "/device-tracker"
      - "/influxdb"
      - "/beszel"
      - "/pingvin"
      - "/grafana"
    schedule:
      interval: "weekly"
