services:
    device-tracker:
        image: ghcr.io/svenvg93/device-tracker:v0.0.2
        container_name: device-tracker
        restart: unless-stopped
        environment:
          TZ: Europe/Amsterdam
          APP_DEBUG: true
          APP_TIMEZONE: Europe/Amsterdam 
          APP_KEY: ${APP_KEY}
          APP_URL: ${APP_URL}
          DISPLAY_TIMEZONE: Europe/Amsterdam
          DB_CONNECTION: sqlite
        networks:
            - tailscale
        volumes:
            - device-tracker:/config
        labels:
          tsdproxy.enable: true
          tsdproxy.container_port: 80

volumes:
  device-tracker:
    name: device-tracker

networks:
  tailscale:  
    name: tailscale