services:
    device-tracker:
        image: ghcr.io/svenvg93/device-tracker:v0.1.0
        container_name: device-tracker
        restart: unless-stopped
        environment:
          TZ: Europe/Amsterdam
          APP_DEBUG: true
          APP_TIMEZONE: Europe/Amsterdam
          APP_KEY: ${APP_KEY}
          APP_URL: ${APP_URL}
          DISPLAY_TIMEZONE: Europe/Amsterdam
          DB_CONNECTION: sqlite
        networks:
            - cftunnel
        volumes:
            - device-tracker:/config

volumes:
  device-tracker:
    name: device-tracker

networks:
  cftunnel:
    name: cftunnel
