global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tailscale'
    scrape_interval: 10s
    static_configs:
      - targets:
          - netprobe01.tail294b9a.ts.net:5252
          - netprobe02.tail294b9a.ts.net:5252
          - netprobe03.tail294b9a.ts.net:5252
          - netprobe04.tail294b9a.ts.net:5252
          - netprobe05.tail294b9a.ts.net:5252
          - netprobe06.tail294b9a.ts.net:5252
          - netprobe07.tail294b9a.ts.net:5252
          - netprobe10.tail294b9a.ts.net:5252
          - cpe-srv.tail294b9a.ts.net:5252
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+):\d+'
        target_label: instance
        replacement: '$1'