apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    user: grafana
    url: http://influxdb:8086
    uid: "eeakieei3m8lce"
    jsonData:
      dbName: netprobe
      httpMode: GET
    secureJsonData:
      password: A2647FC995

  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: "prometheus_ds"
    jsonData:
      httpMethod: GET
      # scrapeInterval defines the minimum time between queries
      timeInterval: "15s"