services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:1.5.0
        container_name: speedtest-tracker
        restart: unless-stopped
        environment:
          TZ: Europe/Amsterdam
          APP_DEBUG: true
          APP_TIMEZONE: Europe/Amsterdam 
          APP_KEY: ${APP_KEY}
          APP_URL: ${APP_URL}
          DISPLAY_TIMEZONE: Europe/Amsterdam
          DB_CONNECTION: sqlite
          SPEEDTEST_SCHEDULE: 6 */2 * * * # Run an test every two hours on minute 6; 00:06, 02:06 etc
          SPEEDTEST_SERVERS: 52365 # Use the Odido Ookla Speedtest server
          PRUNE_RESULTS_OLDER_THAN: 0 # Don't remove old results
          DATETIME_FORMAT: "j M Y, G:i:s" # Use "9 Jan 2025, 11:06:00" as date format for the results table
          CHART_DATETIME_FORMAT: "j/m G:i" # Use "8/01 12:06" as date format for the charts.
          CHART_BEGIN_AT_ZERO: false
        networks:
            - tailscale
        volumes:
            - speedtest-tracker:/config
        labels:
          tsdproxy.enable: "true"
          tsdproxy.container_port: 80

volumes:
  speedtest-tracker:
    name: speedtest-tracker

networks:
  tailscale:  
    name: tailscale
