services:
  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - TZ=Europe/Amsterdam
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION=${GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION}
      - GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION=${GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION}
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=${GF_AUTH_ANONYMOUS_HIDE_VERSION}
    restart: unless-stopped
    networks:
      - cftunnel
      - tailscale
    labels:
      tsdproxy.enable: true
      tsdproxy.name: dashboard
      tsdproxy.container_port: 3000

networks:
  cftunnel:
    name: cftunnel
  tailscale:
    name: tailscale

volumes:
    grafana_data:
      name: grafana_data
