version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - cftunnel

networks:
  cftunnel:
    name: cftunnel