{
 "title": "NetProbes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "record",
    "label": "record",
    "query": "SHOW TAG VALUES WITH KEY=\"record\""
   },
   {
    "name": "target",
    "label": "target",
    "query": "SHOW TAG VALUES WITH KEY=\"target\""
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "SHOW TAG VALUES WITH KEY=\"endpoint\""
   },
   { "name": "Type", "label": "Type", "query": "SHOW TAG VALUES  WITH KEY=Type" },
   {
    "name": "network",
    "label": "Network",
    "query": "SHOW TAG VALUES  WITH KEY=Network WHERE Type =~ /$Type/"
   },
   {
    "name": "cpe",
    "label": "CPE",
    "query": "SHOW TAG VALUES WITH KEY=CPE WHERE Network =~ /$network/ AND Type =~ /$Type/"
   },
   {
    "name": "probe",
    "label": "Probe",
    "query": "SHOW TAG VALUES  WITH  KEY=host WHERE CPE =~ /$cpe/ AND Type =~ /$Type/ AND Network =~ /$network/"
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$target",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "repeat": "target",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" },
        { "condition": "AND", "key": "target::tag", "operator": "=~", "value": "/^$target$/" }
       ]
      },
      {
       "alias": "$tag_host - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "percent_packet_loss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Packet Loss" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" },
        { "condition": "AND", "key": "target::tag", "operator": "=~", "value": "/^$target$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$record",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "repeat": "record",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dns",
       "select": [
        [
         { "params": [ "query_time_ms" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" },
        { "condition": "AND", "key": "record::tag", "operator": "=~", "value": "/^$record$/" }
       ]
      },
      {
       "alias": "$tag_host - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "dns",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Result Code" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" },
        { "condition": "AND", "key": "record::tag", "operator": "=~", "value": "/^$record$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "repeat": "endpoint",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http",
       "select": [
        [
         { "params": [ "response_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" },
        { "condition": "AND", "key": "endpoint::tag", "operator": "=~", "value": "/^$endpoint$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "download_bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 125000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Upload",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "MBs" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "upload_bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 125000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Packet Loss",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_host ",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "packetLoss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Ping Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "ping_latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Speedtest - Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Latency High",
     "type": "timeseries",
     "description": "Highest Latency during the speedtest",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "download_latency_high" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Upload Latency High",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "upload_latency_high" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Download Latency Jitter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "download_latency_jitter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    },
    {
     "title": "Upload Latency Jitter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "upload_latency_jitter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$probe$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}