services:
  influxdb:
    image: influxdb:1.11-alpine
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - TZ=Europe/Amsterdam
      - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUXDB_HTTP_AUTH_ENABLED}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    networks:
      - tailscale
    labels:
      tsdproxy.enable: "true"
      tsdproxy.container_port: 8086

volumes:
    influxdb_data:
      name: influxdb_data

networks:
  tailscale:
    name: tailscale